// ─── DATA ───
export const ITEMS = [
  { id:"ms-0001",sku:"MS-0001",name:"POPLAR No. 1 DE 1''",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:43.11,supplier:"Kumaru",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 353.502" },
  { id:"ms-0002",sku:"MS-0002",name:"POPLAR No. 1 DE 2''",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:51.73,supplier:"Kumaru",minStock:10,currentStock:0,notes:"Pies: 16.4, Total por tabla: 848.372" },
  { id:"ms-0003",sku:"MS-0003",name:"PINO 2DA DE 1'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:215.52,supplier:"Kumaru",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 1767.264" },
  { id:"ms-0004",sku:"MS-0004",name:"POPLAR DE 1'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:68.0,supplier:"Triplay Market",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 557.6" },
  { id:"ms-0005",sku:"MS-0005",name:"ENCINO ROJO FAS DE 1'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:79.0,supplier:"Tenerife",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 647.8" },
  { id:"ms-0006",sku:"MS-0006",name:"PINO 2DA DE 1'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:500.0,supplier:"Vic",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 4100" },
  { id:"ms-0007",sku:"MS-0007",name:"TZALAM DE 2'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:109.0,supplier:"Kumaru",minStock:10,currentStock:0,notes:"Pies: 16.4, Total por tabla: 1787.6" },
  { id:"ms-0008",sku:"MS-0008",name:"IROKO DE 1'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:110.0,supplier:"Triplay Market",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 902" },
  { id:"ms-0009",sku:"MS-0009",name:"TZALAM DE 1'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:100.92,supplier:"Tamahe",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 827.544" },
  { id:"ms-0010",sku:"MS-0010",name:"TZALAM DE 18MM",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:95.0,supplier:"Tamahe",minStock:10,currentStock:0,notes:"Pies: 5.82, Total por tabla: 552.9" },
  { id:"ms-0011",sku:"MS-0011",name:"ENCINO DE 1'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:75.0,supplier:"Punto Kumaru",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 615" },
  { id:"ms-0012",sku:"MS-0012",name:"ENCINO DE 1'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:66.0,supplier:"Tamahe",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 541.2" },
  { id:"ms-0013",sku:"MS-0013",name:"ENCINO DE 1'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:90.0,supplier:"Vic",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 738" },
  { id:"ms-0014",sku:"MS-0014",name:"TEKA DE 1'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:75.0,supplier:"Maderatec",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 615" },
  { id:"ms-0015",sku:"MS-0015",name:"TORNILLO DE 1'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:86.0,supplier:"Maderatec",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 705.2" },
  { id:"ms-0016",sku:"MS-0016",name:"PAROTA DE 4/4'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:44.24,supplier:"Tenerife",minStock:10,currentStock:0,notes:"Pies: 8.2, Total por tabla: 362.768" },
  { id:"ms-0017",sku:"MS-0017",name:"PAROTA DE 6/4'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:44.24,supplier:"Tenerife",minStock:10,currentStock:0,notes:"Pies: 12.3, Total por tabla: 544.152" },
  { id:"ms-0018",sku:"MS-0018",name:"PAROTA DE 8/4'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:44.24,supplier:"Tenerife",minStock:10,currentStock:0,notes:"Pies: 16.4, Total por tabla: 725.536" },
  { id:"ms-0019",sku:"MS-0019",name:"ROSA MORADA DE 2'",category:"Madera Sólida",subcategory:"Madera Sólida",unit:"pie",unitCost:104.4,supplier:"Kumaru",minStock:10,currentStock:0,notes:"Pies: 16.4, Total por tabla: 1712.16" },
  { id:"ty-0020",sku:"TY-0020",name:"TRIPLAY CAOBILLA DE 12 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:597.4,supplier:"Tamahe",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0021",sku:"TY-0021",name:"TRIPLAY CAOBILLA DE 15 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:629.31,supplier:"Kumaru",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0022",sku:"TY-0022",name:"TRIPLAY CAOBILLA DE 5.2 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:232.0,supplier:"Maymavisa",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0023",sku:"TY-0023",name:"TRIPLAY CAOBILLA DE 9 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:426.43,supplier:"Tamahe",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0024",sku:"TY-0024",name:"TRIPLAY CAOBILLA DE 12 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:548.76,supplier:"Tamahe",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0025",sku:"TY-0025",name:"TRIPLAY CAOBILLA DE 15 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:710.89,supplier:"Tamahe",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0026",sku:"TY-0026",name:"TRIPLAY CAOBILLA DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:772.84,supplier:"Tamahe",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0027",sku:"TY-0027",name:"TRIPLAY ENCINO DE 4.2 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:305.0,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0028",sku:"TY-0028",name:"TRIPLAY ENCINO DE 12 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:734.28,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0029",sku:"TY-0029",name:"TRIPLAY ENCINO DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:974.4,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0030",sku:"TY-0030",name:"TRIPLAY EUCALIPTO DE 12 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:435.0,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0031",sku:"TY-0031",name:"TRIPLAY PINO DE 3.2 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:246.0,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0032",sku:"TY-0032",name:"TRIPLAY PINO DE 15 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:559.12,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0033",sku:"TY-0033",name:"TRIPLAY PINO DE 12 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:550.0,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0034",sku:"TY-0034",name:"TRIPLAY PINO DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:719.0,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0035",sku:"TY-0035",name:"TRIPLAY POPLAR DE 5 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:299.79,supplier:"Tamahe",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0036",sku:"TY-0036",name:"TRIPLAY POPLAR DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:885.22,supplier:"Tamahe",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0037",sku:"TY-0037",name:"TRIPLAY POPLAR DE 5 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:242.44,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0038",sku:"TY-0038",name:"TRIPLAY POPLAR DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:792.28,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0039",sku:"TY-0039",name:"TRIPLAY ROSA MORADA DE 4.2 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:1187.84,supplier:"Triplay Market",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0040",sku:"TY-0040",name:"TRIPLAY SAPELI DE 4.2 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:221.56,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0041",sku:"TY-0041",name:"TRIPLAY SAPELI DE 4.2 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:237.0,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0042",sku:"TY-0042",name:"TRIPLAY SAPELI DE 12 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:602.04,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0043",sku:"TY-0043",name:"TRIPLAY SAPELI DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:858.4,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0044",sku:"TY-0044",name:"TRIPLAY ENCINO DE 5.2 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:313.2,supplier:"Tamahe",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0045",sku:"TY-0045",name:"TRIPLAY ENCINO DE 12 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:730.8,supplier:"Tamahe",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0046",sku:"TY-0046",name:"TRIPLAY ENCINO DE 15 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:915.07,supplier:"Tamahe",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0047",sku:"TY-0047",name:"TRIPLAY ENCINO DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:1006.27,supplier:"Tamahe",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0048",sku:"TY-0048",name:"TRIPLAY FRESNO DE 4.2 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:347.0,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0049",sku:"TY-0049",name:"TRIPLAY FRESNO DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:1075.0,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0050",sku:"TY-0050",name:"TRIPLAY TORNILLO DE 4.2 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:333.0,supplier:"Kumaru",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0051",sku:"TY-0051",name:"TRIPLAY TORNILLO DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:1090.0,supplier:"Kumaru",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0052",sku:"TY-0052",name:"TRIPLAY PAROTA DE 4.2 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:404.84,supplier:"Tenerife",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0053",sku:"TY-0053",name:"TRIPLAY PAROTA DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:1282.96,supplier:"Tenerife",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0054",sku:"TY-0054",name:"TRIPLAY ROSA MORADA DE 4.2 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:284.2,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0055",sku:"TY-0055",name:"TRIPLAY ROSA MORADA DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:950.04,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0056",sku:"TY-0056",name:"TRIPLAY ROSA MORADA DE 5 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:360.0,supplier:"Kumaru",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0057",sku:"TY-0057",name:"TRIPLAY ROSA MORADA DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:1250.0,supplier:"Kumaru",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0058",sku:"TY-0058",name:"TRIPLAY TZALAM DE 18 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:1340.0,supplier:"Tamahe",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"ty-0059",sku:"TY-0059",name:"TRIPLAY TZALAM DE 16 mm",category:"Madera",subcategory:"Triplay",unit:"hoja",unitCost:1400.0,supplier:"Triplay Market",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"md-0060",sku:"MD-0060",name:"TECNO MDF NEGRO BRUNO DE 5.5 mm",category:"Madera",subcategory:"MDF",unit:"hoja",unitCost:505.76,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"md-0061",sku:"MD-0061",name:"TECNO MDF NEGRO BRUNO DE 15 mm",category:"Madera",subcategory:"MDF",unit:"hoja",unitCost:754.0,supplier:"Vic",minStock:3,currentStock:0,notes:"HOJA DE 122X240 CM" },
  { id:"cu-0062",sku:"CU-0062",name:"CHAPA ENCINO ROJO DE 50MM",category:"Madera",subcategory:"Cubrecanto",unit:"pz",unitCost:12.0,supplier:"Vic",minStock:10,currentStock:0,notes:"" },
  { id:"cu-0063",sku:"CU-0063",name:"CHAPA ENCINO ROJO DE 19MM",category:"Madera",subcategory:"Cubrecanto",unit:"pz",unitCost:5.0,supplier:"Vic",minStock:10,currentStock:0,notes:"" },
  { id:"cu-0064",sku:"CU-0064",name:"CHAPA NEGRO BRUNO rollo DE 19MM",category:"Madera",subcategory:"Cubrecanto",unit:"pz",unitCost:2.76,supplier:"Vic",minStock:10,currentStock:0,notes:"" },
  { id:"cu-0065",sku:"CU-0065",name:"CHAPA NEGRO BRUNO A GRANEL DE 50MM",category:"Madera",subcategory:"Cubrecanto",unit:"pz",unitCost:5.0,supplier:"Bajce",minStock:10,currentStock:0,notes:"" },
  { id:"cu-0066",sku:"CU-0066",name:"CHAPA ENCINO DE 40X2.44",category:"Madera",subcategory:"Cubrecanto",unit:"pz",unitCost:208.8,supplier:"Tamahe",minStock:5,currentStock:0,notes:"" },
  { id:"cu-0067",sku:"CU-0067",name:"CHAPA ENCINO DE 30X2.50",category:"Madera",subcategory:"Cubrecanto",unit:"pz",unitCost:115.0,supplier:"Vic",minStock:5,currentStock:0,notes:"" },
  { id:"cu-0068",sku:"CU-0068",name:"CUBRE CANTO POPLAR 2' DE 1 metro",category:"Madera",subcategory:"Cubrecanto",unit:"pz",unitCost:12.0,supplier:"Sin Proveedor",minStock:10,currentStock:0,notes:"" },
  { id:"cu-0069",sku:"CU-0069",name:"CHAPA ROSA MORADA",category:"Madera",subcategory:"Cubrecanto",unit:"pz",unitCost:200.0,supplier:"Kumaru",minStock:5,currentStock:0,notes:"" },
  { id:"vi-0070",sku:"VI-0070",name:"CRISTAL CLARO DE 6 mm",category:"Otros",subcategory:"Vidrio",unit:"pz",unitCost:1318.16,supplier:"Alucan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0071",sku:"S88",name:"SELLO PEMKO PERIMETRAL 20' S88 600 CM NEGRO",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:690.0,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0072",sku:"483.01.735",name:"BISAGRA HAFELE BID. 35 MM RECTA 4 PUNTOS DE SUJECIÓN",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:25.0,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0073",sku:"HA3101",name:"BISAGRA HARDSAN 3101 INOX 3 X 3",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:50.0,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0074",sku:"02001BOC",name:"BRIDA P/TUBO OVALADO CROMO MOD. 03",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:5.85,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0075",sku:"AMI-23",name:"RESBALON C/CLAVO C/GOMA NEGRA 20 MM",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:2.5,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0076",sku:"MX3028",name:"MIRILLA PHILLIPS 200° CROMO",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:93.65,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0077",sku:"MX85259",name:"TOPE MEDIA LUNA TESA ACERO INOX #1",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:76.0,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0078",sku:"L660",name:"TUBO OVALADO ALUM.3.00 MTS ASTREADO REFORZADO",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:400.17,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0079",sku:"A3686",name:"CUBRE POLVO AUTOMATICO INOX 1500 MM AMI",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:750.0,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0080",sku:"0402-273",name:"JALADERA CERRAJES 0402-273 MOD. 4004Z29",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:56.0,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0081",sku:"0402-277",name:"JALADERA CERRAJES 0402-277 MOD. 4005Z34",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:52.0,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0082",sku:"HA3101",name:"BISAGRA HARDSAN 3101 INOX 3 X 3.",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:48.26,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0083",sku:"7206]",name:"BISAGRA DEXTER 7206 2.5 X 2.5 INOX",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:59.55,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0084",sku:"HA3108",name:"BISAGRA HARDSAN INOX 2' X 2' x 1.2 MM",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:20.88,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0085",sku:"TR43200",name:"BISAGRA TRUPER INOX 1 1/2' MOD.BR-154 43200",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:16.55,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0086",sku:"0601-486",name:"BISAGRA CERRAJES BID. 35 MM CURVA 0601-486",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:21.62,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0087",sku:"0303-084",name:"CORREDERA CERRAJES EXTENSION 40 CM 0303-084",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:64.82,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0088",sku:"VK15536",name:"PIJA VEKER 15536 5/8",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:14.99,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0089",sku:"VK15502",name:"PIJA VEKER P/TABLAROCA 8 X 1 1/4' 15502.",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:19.21,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0090",sku:"VK15504",name:"PIJA VEKER P/TABLAROCA 8 X 2' 15504.",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:30.98,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0091",sku:"HA2102",name:"RESBALON IMAN HARDSAN SIMPLE NEGRO",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:9.28,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0092",sku:"L657",name:"TUBO ALUMINIO 1' ANODIZADO 6 MTS.",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:392.83,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0093",sku:"494.02.646",name:"CORR. HAFELE EXTENSION CIERRE SUAVE 550 MM",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:275.62,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0094",sku:"315.07.023",name:"BISAGRA HAFELE BID. 35 MM RECTA SOFT CIERRE LENTO",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:67.69,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0095",sku:"494.02.645",name:"CORR. HAFELE EXTENSION CIERRE SUAVE 500 MM",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:233.95,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0096",sku:"MX88625",name:"TOPE TESA INOX MOD. 2",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:139.84,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0097",sku:"MX86490",name:"CILINDRO TESA T-5 LLAVE LLAVE 60 MM N.S",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:456.99,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0098",sku:"AM22620",name:"MANIJA AMIG TUBULAR 7RBX INOX",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:315.49,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0099",sku:"A71773",name:"MIRILLA AMIG 2-14 DE 25A 42 CR MATE 7177",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:212.72,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0100",sku:"WC-70-TK",name:"CILINDRO ETC INOX P/BAÑO 70 MM",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:271.15,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0101",sku:"A146",name:"TUBO OVALADO ALUM.6.00 MTS ASTREADO REFORZADO",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:674.77,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0102",sku:"494.02.644",name:"CORR. HAFELE EXTENSION CIERRE SUAVE 450 MM",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:207.64,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0103",sku:"315.07.024",name:"BISAGRA HAFELE BID. 35 MM SEMICURVA SOFT CIERRE LENTO",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:64.12,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0104",sku:"494.02.643",name:"CORR. HAFELE EXTENSION CIERRE SUAVE 400 MM",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:189.75,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0105",sku:"315.07.025",name:"BISAGRA HAFELE BID. 35 MM CURVA SOFT CIERRE LENTO",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:64.12,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0106",sku:"0402-311",name:"JALADERA CERRAJES 0402-311 MOD.4005Z15",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:50.69,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0107",sku:"AMI-22-2",name:"RESBALON C/CLAVO PLASTICO CAFE 25 MM",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:2.32,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0108",sku:"[106608000",name:"VENTOSAS DE ALUM. DOBLE (80KG) 1066.",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:1151.67,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0109",sku:"0402-316",name:"JALADERA CERRAJES 0402-316 MOD. 4005A91",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:48.72,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0110",sku:"133.50.223",name:"JALADERA BOTON BLACKROCK 34 MM NEGRO BRONCE BP55270BBR.",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:143.65,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0111",sku:"D1009.48.09.Neg",name:"RESBALON TOUCH DOBLE NEGRO D1009",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:25.23,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0112",sku:"[8413023007246",name:"RESBALON IMAN AMIG CAFE 724",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:9.92,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0113",sku:"[7805738021708",name:"CARRETILLA DN 80 SR DUCASSE",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:197.22,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0114",sku:"[4033520024",name:"RIEL U-21 ALUMINIO X 2 MTS. DUCASSE",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:344.54,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0115",sku:"2175005BL",name:"PASADOR HERRALUM DE LUJO MOD. 2175 BL..",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:34.2,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0116",sku:"[64947",name:"JALADERA RISH 8124/64 NEGRO TEXT",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:38.33,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0117",sku:"311.90.509",name:"BISAGRA HAFELE BID. 35 MM CURVA.",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:34.8,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0118",sku:"422.87.903",name:"CORR. HAFELE EXTENSION 40 CMS. 16",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:29.0,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0119",sku:"M5516-CL",name:"MENSULA HARDSAN TRANSPARENTE 5516CL.",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:2.34,supplier:"Hardsan",minStock:10,currentStock:0,notes:"" },
  { id:"he-0120",sku:"0402-276",name:"JALADERA CERRAJES 0402-276 MOD. 4005Z02.",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:50.69,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0121",sku:"0402-275",name:"JALADERA CERRAJES 0402-275 MOD. 4005Z11",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:54.52,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0122",sku:"MX33",name:"CERR. PHILLIPS MOD. 250 C.",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:197.2,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0123",sku:"03005RDBGC",name:"RESBALON DOBLE BALA GDE. CROMO SAT",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:51.07,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0124",sku:"494.02.642",name:"CORR. HAFELE EXTENSION CIERRE SUAVE 350MM",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:191.66,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"he-0125",sku:"0806-044",name:"BISAGRA CERRAJES 0806-044 3 X 3 C/BALEROS INOX (PAQ. C/3 PIEZAS).",category:"Herrajes",subcategory:"Herrajes",unit:"pz",unitCost:166.69,supplier:"Hardsan",minStock:5,currentStock:0,notes:"" },
  { id:"fe-0126",sku:"11455",name:"Broca para router recta 2 filos 3/8",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:85.0,supplier:"Truper",minStock:5,currentStock:0,notes:"" },
  { id:"fe-0127",sku:"11474",name:"Broca para router, redondeado, 1-1/2' con balero",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:108.99,supplier:"Truper",minStock:5,currentStock:0,notes:"" },
  { id:"fe-0128",sku:"11457",name:"Broca para router, recta 2 filos, 5/8', Truper",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:72.0,supplier:"Truper",minStock:5,currentStock:0,notes:"" },
  { id:"fe-0129",sku:"162843",name:"RESISTOL 5000 4L SUPERFICIES",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:715.0,supplier:"Home Depot",minStock:5,currentStock:0,notes:"" },
  { id:"fe-0130",sku:"44342",name:"PIJA PLANA CRUZ PAVONADO 3/4X8 (100PZ)",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:25.0,supplier:"Truper",minStock:10,currentStock:0,notes:"" },
  { id:"fe-0131",sku:"44343",name:"PIJA PLANA CRUZ PAVONADO 1X8 (100PZ)",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:30.0,supplier:"Truper",minStock:10,currentStock:0,notes:"" },
  { id:"fe-0132",sku:"44344",name:"PIJA PLANA CRUZ PAVONADO 1-1/4X8 (100PZ)",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:36.0,supplier:"Truper",minStock:10,currentStock:0,notes:"" },
  { id:"fe-0133",sku:"44345",name:"PIJA PLANA CRUZ PAVONADO 1-1/2X8 (100PZ)",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:41.0,supplier:"Truper",minStock:10,currentStock:0,notes:"" },
  { id:"fe-0134",sku:"44346",name:"PIJA PLANA CRUZ PAVONADO 1-3/4X8 (100PZ)",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:49.0,supplier:"Truper",minStock:10,currentStock:0,notes:"" },
  { id:"fe-0135",sku:"44347",name:"PIJA PLANA CRUZ PAVONADO 2X8' (100PZ)",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:55.0,supplier:"Truper",minStock:5,currentStock:0,notes:"" },
  { id:"fe-0136",sku:"48690",name:"PIJA PLANA CRUZ PAVONADO 2-1/2X8' (100PZ)",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:70.0,supplier:"Truper",minStock:5,currentStock:0,notes:"" },
  { id:"fe-0137",sku:"48691",name:"PIJA PLANA CRUZ PAVONADO 3X8' (100PZ)",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:87.0,supplier:"Truper",minStock:5,currentStock:0,notes:"" },
  { id:"fe-0138",sku:"RE378",name:"PEGAMENTOFURIA BLANCO18kgs",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:1357.2,supplier:"Vic",minStock:5,currentStock:0,notes:"" },
  { id:"fe-0139",sku:"204936",name:"RESISTOL NO MÁS CLAVOS",category:"Ferretería",subcategory:"Ferretería",unit:"pz",unitCost:130.0,supplier:"Home Depot",minStock:5,currentStock:0,notes:"" },
  { id:"bp-0140",sku:"611843",name:"3M 26336 CINTA MASKING 1' VERDE 233 PZ",category:"Barniz y Pintura",subcategory:"Cinta de enmascarar",unit:"pz",unitCost:99.64,supplier:"Pinturas Martinez",minStock:5,currentStock:0,notes:"" },
  { id:"bp-0141",sku:"530203",name:"CU#A MET. MEDIANA S/MANGO PZ",category:"Barniz y Pintura",subcategory:"Cuñas",unit:"pz",unitCost:4.18,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0142",sku:"EX-0775",name:"ESM. X-TRONG AMARILLO OXIDO LT",category:"Barniz y Pintura",subcategory:"Pinturas de esmalte",unit:"lt",unitCost:162.17,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0143",sku:"EX-0555",name:"ESM. X-TRONG ROJO OXIDO LT",category:"Barniz y Pintura",subcategory:"Pinturas de esmalte",unit:"lt",unitCost:162.17,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0144",sku:"LI-0103G",name:"LACA INDUS. AMARILLO OCRE 4 LTS.",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:745.65,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0145",sku:"LI-0102G",name:"LACA INDUS. NEGRA 4 LTS.",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:745.65,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0146",sku:"538637",name:"LAM COLADOR DE METAL P/PINTURA PZ",category:"Barniz y Pintura",subcategory:"Tela de fique o estopa",unit:"pz",unitCost:40.37,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0147",sku:"515052",name:"LIJA DE ROLLO FANDELI # 50 X 1 CM.",category:"Barniz y Pintura",subcategory:"Abrasivos y medios de abrasivo",unit:"mt",unitCost:3.71,supplier:"Pinturas Martinez",minStock:3,currentStock:0,notes:"" },
  { id:"bp-0148",sku:"515082",name:"LIJA DE ROLLO FANDELI # 80 X 1 CM.",category:"Barniz y Pintura",subcategory:"Abrasivos y medios de abrasivo",unit:"mt",unitCost:3.13,supplier:"Pinturas Martinez",minStock:3,currentStock:0,notes:"" },
  { id:"bp-0149",sku:"TS-6112",name:"MANCHASAYER EARLY AMERICAN LT.",category:"Barniz y Pintura",subcategory:"Tinturas",unit:"lt",unitCost:185.0,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0150",sku:"524363",name:"NORTON 31544 A275 DISCO G-220 VELCRO 5' BCO. PZ.",category:"Barniz y Pintura",subcategory:"Lija de disco",unit:"pz",unitCost:13.69,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0151",sku:"524706",name:"NORTON 44275 T489 LIJA SHS P220 AGUA PZ.",category:"Barniz y Pintura",subcategory:"Lija de disco",unit:"pz",unitCost:12.06,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0152",sku:"524709",name:"NORTON 44285 T489 LIJA SHS P320 AGUA PZ",category:"Barniz y Pintura",subcategory:"Lija de disco",unit:"pz",unitCost:12.06,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0153",sku:"KF-1010CU",name:"PRIMARIO SAYER BLANCO 19 LTS",category:"Barniz y Pintura",subcategory:"Pinturas y tapa poros",unit:"lt",unitCost:232.76,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0154",sku:"KF-0500G",name:"RESANADOR SAYER ULTRA C/CATAL. 4 LTS",category:"Barniz y Pintura",subcategory:"Pinturas y tapa poros",unit:"lt",unitCost:177.65,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0155",sku:"511102",name:"RESISTOL 5000 4 LTS.",category:"Barniz y Pintura",subcategory:"Otros adhesivos y selladores",unit:"lt",unitCost:257.26,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0156",sku:"UC-1000G",name:"(DESC) ENDURESAYER 4 LTS.",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:336.86,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0157",sku:"BP-0157",name:"ADITIVO SAYER BALANCEADOR MICAS SAYER 250ML",category:"Barniz y Pintura",subcategory:"Barniz",unit:"ml",unitCost:112.4,supplier:"Pinturas Martinez",minStock:3,currentStock:0,notes:"" },
  { id:"bp-0158",sku:"D-0102",name:"AGUARRAS SAYER",category:"Barniz y Pintura",subcategory:"Diluyentes para pinturas y barnices",unit:"lt",unitCost:83.17,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0159",sku:"R-0129/A",name:"AISLASAYER LT",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:227.24,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0160",sku:"KC-0511GR",name:"CATAL. SAYER ULTRA ROJO 95GR",category:"Barniz y Pintura",subcategory:"Pinturas y tapa poros",unit:"lt",unitCost:82.59,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0161",sku:"R-0129/B",name:"CATALIZADOR P/AISLASAYER LT",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:227.24,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0162",sku:"N-0050/BCU",name:"CATALIZADOR PARA N-0050/A",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:208.48,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0163",sku:"N-0050/BCU",name:"CATALIZADOR PARA N-0050/A 19 LTS.",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:208.48,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0164",sku:"A-1005959",name:"COLADORES DESECHABLES PZ",category:"Barniz y Pintura",subcategory:"Aplicadores de pintura y accesorios",unit:"pz",unitCost:3.13,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0165",sku:"523404",name:"CORONA BROCHA REAL 2' PZ.",category:"Barniz y Pintura",subcategory:"Brochas",unit:"pz",unitCost:27.14,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0166",sku:"523407",name:"CORONA BROCHA REAL 4' PZ.",category:"Barniz y Pintura",subcategory:"Brochas",unit:"pz",unitCost:63.1,supplier:"Pinturas Martinez",minStock:5,currentStock:0,notes:"" },
  { id:"bp-0167",sku:"528053",name:"CORONA PINCEL CAMELLO PLANO #3 PZ.",category:"Barniz y Pintura",subcategory:"Pinceles de utilidad",unit:"pz",unitCost:16.94,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0168",sku:"528055",name:"CORONA PINCEL CAMELLO PLANO #5 PZ.",category:"Barniz y Pintura",subcategory:"Pinceles de utilidad",unit:"pz",unitCost:27.14,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0169",sku:"528041",name:"CORONA PINCEL CAMELLO REDONDO #1 PZ.",category:"Barniz y Pintura",subcategory:"Pinceles de utilidad",unit:"pz",unitCost:12.53,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0170",sku:"528042",name:"CORONA PINCEL CAMELLO REDONDO #2 PZ.",category:"Barniz y Pintura",subcategory:"Pinceles de utilidad",unit:"pz",unitCost:13.92,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0171",sku:"528043",name:"CORONA PINCEL CAMELLO REDONDO #3 PZ.",category:"Barniz y Pintura",subcategory:"Pinceles de utilidad",unit:"pz",unitCost:16.94,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0172",sku:"530201",name:"CUÑA MET. CHICA S/MANGO PZ.",category:"Barniz y Pintura",subcategory:"Cuñas",unit:"pz",unitCost:3.6,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0173",sku:"BP-0173",name:"EMPAQUE PARA BASO LONA",category:"Barniz y Pintura",subcategory:"Barniz",unit:"pz",unitCost:4.99,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0174",sku:"UC-1000",name:"ENDURESAYER",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:316.5,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0175",sku:"UC-1000CU",name:"ENDURESAYER 19 LTS",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:250.8,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0176",sku:"UC-1000G5",name:"ENDURESAYER 5 LTS",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:336.86,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0177",sku:"UC-1010CU",name:"ENDURESAYER P/UREMATE 19 LTS.",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:268.11,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0178",sku:"EX-0200",name:"ESM. X-TRONG BLANCO DIR BRILL LT",category:"Barniz y Pintura",subcategory:"Pinturas de esmalte",unit:"lt",unitCost:162.17,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0179",sku:"EX-TR1",name:"ESM. X-TRONG IGUALADO LT.",category:"Barniz y Pintura",subcategory:"Pinturas de esmalte",unit:"lt",unitCost:162.17,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0180",sku:"EX-0100",name:"ESM. X-TRONG NEGRO BRILL. LT",category:"Barniz y Pintura",subcategory:"Pinturas de esmalte",unit:"lt",unitCost:162.17,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0181",sku:"531211",name:"ESTOPA DE ALGODÓN",category:"Barniz y Pintura",subcategory:"Tela de fique o estopa",unit:"kl",unitCost:51.5,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0182",sku:"BP-0182",name:"FONDO CATALIZABLE TRANSPARENTE  N-0050 (20LT)",category:"Barniz y Pintura",subcategory:"Barniz",unit:"lt",unitCost:3961.05,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0183",sku:"N-0050/ACU",name:"FONDO CATALIZABLE TRANSPARENTE 19 LTS",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:208.48,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0184",sku:"N-0050/ACU",name:"FONDO CATALIZABLE TRANSPARENTE 19 LTS.",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:208.48,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0185",sku:"BP-0185",name:"FONDO POLIURETANO MATE UM-1015 (19L)",category:"Barniz y Pintura",subcategory:"Barniz",unit:"lt",unitCost:3997.82,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0186",sku:"LI-0103",name:"LACA INDUS. AMARILLO OCRE LT",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:186.41,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0187",sku:"LI-0101G",name:"LACA INDUS. BLANCA 4 LTS",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:745.65,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0188",sku:"LI-0101",name:"LACA INDUS. BLANCA LT",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:181.79,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0189",sku:"LI-0101",name:"LACA INDUS. BLANCA LT",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:191.4,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0190",sku:"LI-LC1",name:"LACA INDUS. IGUALADO",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:210.54,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0191",sku:"LI-LC1CU",name:"LACA INDUS. IGUALADO 19 LTS",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:199.97,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0192",sku:"LI-0102",name:"LACA INDUS. NEGRA LT.",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:191.4,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0193",sku:"LI-0106G",name:"LACA INDUS. ROJO OXIDO 4 LTS.",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:745.65,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0194",sku:"LI-0106",name:"LACA INDUS. ROJO OXIDO LT",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:191.4,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0195",sku:"538638",name:"LAM REPUESTO P/COLADOR PZ",category:"Barniz y Pintura",subcategory:"Coladores de pintura",unit:"pz",unitCost:20.07,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0196",sku:"515060",name:"LIJA DE ROLLO FANDELI # 60 X MT",category:"Barniz y Pintura",subcategory:"Abrasivos y medios de abrasivo",unit:"mt",unitCost:315.87,supplier:"Pinturas Martinez",minStock:3,currentStock:0,notes:"" },
  { id:"bp-0197",sku:"515080",name:"LIJA DE ROLLO FANDELI # 80 X MT",category:"Barniz y Pintura",subcategory:"Abrasivos y medios de abrasivo",unit:"mt",unitCost:288.61,supplier:"Pinturas Martinez",minStock:3,currentStock:0,notes:"" },
  { id:"bp-0198",sku:"LN-0001",name:"NITROLACA BRILL. BLANCA",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:276.66,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0199",sku:"524362",name:"NORTON 31545 A275 DISCO G-180 VELCRO 5' BCO. PZ",category:"Barniz y Pintura",subcategory:"Lija de disco",unit:"pz",unitCost:13.69,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0200",sku:"524361",name:"NORTON 31546 A275 DISCO G-150 VELCRO 5' BCO. PZ.",category:"Barniz y Pintura",subcategory:"Lija de disco",unit:"pz",unitCost:13.69,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0201",sku:"524358",name:"NORTON 31549 A275 DISCO G-80 VELCRO 5' BCO. PZ",category:"Barniz y Pintura",subcategory:"Lija de disco",unit:"pz",unitCost:13.69,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0202",sku:"524278",name:"NORTON 31626 A275 LIJA G-320 PZ.",category:"Barniz y Pintura",subcategory:"Lija manual",unit:"pz",unitCost:15.08,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0203",sku:"524275",name:"NORTON 31629 A275 LIJA G-220 PZ",category:"Barniz y Pintura",subcategory:"Lija manual",unit:"pz",unitCost:15.08,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0204",sku:"524274",name:"NORTON 31630 A275 LIJA G-180 PZ.",category:"Barniz y Pintura",subcategory:"Lija manual",unit:"pz",unitCost:15.08,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0205",sku:"524710",name:"NORTON 44269 T489 LIJA SHS P360 AGUA PZ.",category:"Barniz y Pintura",subcategory:"Lija manual",unit:"pz",unitCost:11.95,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0206",sku:"524707",name:"NORTON 44277 T489 LIJA SHS P240 AGUA PZ.",category:"Barniz y Pintura",subcategory:"Lija manual",unit:"pz",unitCost:12.18,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0207",sku:"524705",name:"NORTON 44281 T489 LIJA SHS P180 AGUA PZ",category:"Barniz y Pintura",subcategory:"Lija manual",unit:"pz",unitCost:12.88,supplier:"Pinturas Martinez",minStock:10,currentStock:0,notes:"" },
  { id:"bp-0208",sku:"524549",name:"NORTON 9770 MASKING 2' VERDE PZ.",category:"Barniz y Pintura",subcategory:"Cinta de enmascarar",unit:"pz",unitCost:208.45,supplier:"Pinturas Martinez",minStock:5,currentStock:0,notes:"" },
  { id:"bp-0209",sku:"3203012",name:"PLASTER BLANCO TEX-ZEL 4 LTS",category:"Barniz y Pintura",subcategory:"Sellantes",unit:"lt",unitCost:707.95,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0210",sku:"KF-0500G",name:"RESANADOR SAYER ULTRA C/CATAL. 4 LTS.",category:"Barniz y Pintura",subcategory:"Pinturas y tapa poros",unit:"lt",unitCost:177.65,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0211",sku:"RL-0014",name:"RESANALACK NOGAL LT",category:"Barniz y Pintura",subcategory:"Pinturas y tapa poros",unit:"lt",unitCost:158.69,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0212",sku:"RL-0022",name:"RESANALACK PINO",category:"Barniz y Pintura",subcategory:"Pinturas y tapa poros",unit:"lt",unitCost:158.69,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0213",sku:"BP-0213",name:"RESANALACK ROBLE 250 ML",category:"Barniz y Pintura",subcategory:"Barniz",unit:"ml",unitCost:47.56,supplier:"Pinturas Martinez",minStock:3,currentStock:0,notes:"" },
  { id:"bp-0214",sku:"BP-0214",name:"RESISTOL 5000 (4L)",category:"Barniz y Pintura",subcategory:"Barniz",unit:"lt",unitCost:1029.04,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0215",sku:"511122",name:"RESISTOL 950 AMARILLO PROFESIONAL 4 KG.",category:"Barniz y Pintura",subcategory:"Otros adhesivos y selladores",unit:"lt",unitCost:143.69,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0216",sku:"D-0200",name:"RETARDADOR P/LACA",category:"Barniz y Pintura",subcategory:"Diluyentes para pinturas y barnices",unit:"lt",unitCost:217.73,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0217",sku:"EK-1100G",name:"ROCKET SEC. RAP. NEGRO MATE 4 LTS",category:"Barniz y Pintura",subcategory:"Pinturas de esmalte",unit:"lt",unitCost:233.42,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0218",sku:"NS-44/300CU",name:"SELLALACK CONCENTRADO 19 LTS.",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:175.13,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0219",sku:"EZ-0001",name:"SOLUCION MATIZANTE",category:"Barniz y Pintura",subcategory:"Pinturas de esmalte",unit:"lt",unitCost:409.13,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0220",sku:"D-0500",name:"SOLVENTE P/POLIURETANO",category:"Barniz y Pintura",subcategory:"Diluyentes para pinturas y barnices",unit:"lt",unitCost:132.59,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0221",sku:"BP-0221",name:"SOLVENTE P/POLIURETANO 20 LT. (D-500)",category:"Barniz y Pintura",subcategory:"Barniz",unit:"lt",unitCost:2419.41,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0222",sku:"490011",name:"TALCO INDUSTRIAL KG",category:"Barniz y Pintura",subcategory:"Barnices",unit:"kg",unitCost:35.84,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0223",sku:"506352",name:"THINNER AMERICANO",category:"Barniz y Pintura",subcategory:"Diluyentes para pinturas y barnices",unit:"lt",unitCost:50.09,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0224",sku:"BP-0224",name:"THINNER AMERICANO 200LT",category:"Barniz y Pintura",subcategory:"Barniz",unit:"lt",unitCost:10018.11,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0225",sku:"BP-0225",name:"THINNER AMERICANO LT",category:"Barniz y Pintura",subcategory:"Barniz",unit:"lt",unitCost:52.43,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0226",sku:"D-0002CU",name:"THINNER SAYER TIPO ESTANDAR 20 LTS.",category:"Barniz y Pintura",subcategory:"Diluyentes para pinturas y barnices",unit:"lt",unitCost:52.4,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0227",sku:"531207",name:"TRAPO INDUSTRIAL",category:"Barniz y Pintura",subcategory:"Trapos",unit:"kl",unitCost:61.13,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0228",sku:"UM-1015CU",name:"URESAYER MATE 19 LTS",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:210.41,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" },
  { id:"bp-0229",sku:"UP-1001CU",name:"URESAYER PRIMER BLANCO",category:"Barniz y Pintura",subcategory:"Barnices",unit:"lt",unitCost:265.77,supplier:"Pinturas Martinez",minStock:2,currentStock:0,notes:"" }
];

export const CATEGORIES = [
  { id:"c1",name:"Madera Sólida",subs:["Madera Sólida"] },
  { id:"c2",name:"Madera",subs:["Triplay", "MDF", "Cubrecanto"] },
  { id:"c3",name:"Otros",subs:["Vidrio"] },
  { id:"c4",name:"Herrajes",subs:["Herrajes"] },
  { id:"c5",name:"Ferretería",subs:["Ferretería"] },
  { id:"c6",name:"Barniz y Pintura",subs:["Cinta de enmascarar", "Cuñas", "Pinturas de esmalte", "Barnices", "Tela de fique o estopa", "Abrasivos y medios de abrasivo", "Tinturas", "Lija de disco", "Pinturas y tapa poros", "Otros adhesivos y selladores", "Barniz", "Diluyentes para pinturas y barnices", "Aplicadores de pintura y accesorios", "Brochas", "Pinceles de utilidad", "Coladores de pintura", "Lija manual", "Sellantes", "Trapos"] },
];

export const SUPPLIERS = [
  { id:"s1",company:"Kumaru",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s2",company:"Triplay Market",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s3",company:"Tenerife",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s4",company:"Vic",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s5",company:"Tamahe",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s6",company:"Punto Kumaru",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s7",company:"Maderatec",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s8",company:"Maymavisa",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s9",company:"Bajce",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s10",company:"Sin Proveedor",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s11",company:"Alucan",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s12",company:"Hardsan",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s13",company:"Truper",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s14",company:"Home Depot",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
  { id:"s15",company:"Pinturas Martinez",contact:"",email:"",phone:"",payment:"",leadTime:3,rating:0,active:true },
];


export const REQUISITIONS = [
  { id: "r1", number: "REQ-2026-0042", title: "Material cocina López", project: "Cocina López", requester: "Carlos Ruiz", priority: "high", status: "pending_approval", neededBy: "2026-02-28",
    items: [
      { id: "ri1", itemId: "i1", name: "Triplay Pino 18mm (4×8ft)", qty: 10, unit: "hoja", estCost: 450, type: "catalog", notes: "" },
      { id: "ri2", itemId: "i3", name: "MDF 15mm (4×8ft)", qty: 5, unit: "hoja", estCost: 280, type: "catalog", notes: "" },
      { id: "ri3", itemId: null, name: "Bisagra push-open para cristal 8mm", qty: 12, unit: "pza", estCost: null, type: "free_text", notes: "Vi unas en Herrajes y Más, preguntarle a Laura" },
      { id: "ri4", itemId: "i6", name: "Pegamento Blanco 1L", qty: 2, unit: "litro", estCost: 175, type: "catalog", notes: "" },
    ], estimatedCost: 6135, createdAt: "2026-02-24" },
  { id: "r2", number: "REQ-2026-0041", title: "Herrajes closet master", project: "Closet Martínez", requester: "Carlos Ruiz", priority: "medium", status: "pending_approval", neededBy: "2026-03-05",
    items: [
      { id: "ri5", itemId: "i4", name: "Bisagra Oculta 35mm", qty: 24, unit: "pza", estCost: 35, type: "catalog", notes: "" },
      { id: "ri6", itemId: "i13", name: "Corredera Telescópica 35cm", qty: 6, unit: "par", estCost: 145, type: "catalog", notes: "" },
      { id: "ri7", itemId: null, name: "Jaladera acero inox tubular 192mm", qty: 8, unit: "pza", estCost: null, type: "free_text", notes: "Acabado cepillado, no espejo" },
      { id: "ri8", itemId: null, name: "Tubo oval cromado p/closet 1.2m", qty: 3, unit: "pza", estCost: null, type: "free_text", notes: "" },
      { id: "ri9", itemId: "i5", name: "Tornillo Madera 3 pulgadas", qty: 1, unit: "caja", estCost: 85, type: "catalog", notes: "" },
      { id: "ri10", itemId: null, name: "Soporte lateral tubo oval cromado", qty: 6, unit: "pza", estCost: null, type: "free_text", notes: "Que haga juego con el tubo" },
    ], estimatedCost: 3420, createdAt: "2026-02-23" },
  { id: "r3", number: "REQ-2026-0043", title: "Acabados mueble TV", project: "Mueble TV Sánchez", requester: "Miguel Torres", priority: "urgent", status: "pending_approval", neededBy: "2026-02-26",
    items: [
      { id: "ri11", itemId: "i7", name: "Barniz Transparente Mate 1L", qty: 3, unit: "litro", estCost: 320, type: "catalog", notes: "" },
      { id: "ri12", itemId: "i8", name: "Lija Grano 120", qty: 10, unit: "pza", estCost: 25, type: "catalog", notes: "" },
      { id: "ri13", itemId: null, name: "Tinte color nogal para madera 500ml", qty: 2, unit: "pza", estCost: null, type: "free_text", notes: "Marca Comex o similar" },
    ], estimatedCost: 1890, createdAt: "2026-02-24" },
  { id: "r4", number: "REQ-2026-0040", title: "Tableros escritorio", project: "Escritorio Pérez", requester: "Carlos Ruiz", priority: "medium", status: "approved", neededBy: "2026-03-01",
    items: [{ id: "x1", itemId: "i12", name: "Melamina Blanca 16mm", qty: 4, unit: "hoja", estCost: 520, type: "catalog", notes: "" }], estimatedCost: 4200, createdAt: "2026-02-22" },
  { id: "r5", number: "REQ-2026-0039", title: "Madera librero", project: "Librero García", requester: "Miguel Torres", priority: "low", status: "approved", neededBy: "2026-03-10",
    items: [{ id: "x2", itemId: "i9", name: "Tabla Pino 2×4", qty: 12, unit: "pieza", estCost: 95, type: "catalog", notes: "" }], estimatedCost: 2800, createdAt: "2026-02-21" },
  { id: "r6", number: "REQ-2026-0038", title: "Herrajes cocina Díaz", project: "Cocina Díaz", requester: "Carlos Ruiz", priority: "high", status: "in_progress", neededBy: "2026-02-27",
    items: [{ id: "x3", itemId: "i4", name: "Bisagra Oculta 35mm", qty: 30, unit: "pza", estCost: 35, type: "catalog", notes: "" }], estimatedCost: 8500, createdAt: "2026-02-18" },
  { id: "r7", number: "REQ-2026-0037", title: "MDF baño Herrera", project: "Baño Herrera", requester: "Miguel Torres", priority: "medium", status: "in_progress", neededBy: "2026-03-02",
    items: [{ id: "x4", itemId: "i3", name: "MDF 15mm", qty: 3, unit: "hoja", estCost: 280, type: "catalog", notes: "" }], estimatedCost: 3100, createdAt: "2026-02-17" },
  { id: "r8", number: "REQ-2026-0035", title: "Material puerta", project: "Puerta Ramírez", requester: "Miguel Torres", priority: "high", status: "completed", neededBy: "2026-02-20",
    items: [{ id: "x6", itemId: "i9", name: "Tabla Pino", qty: 8, unit: "pieza", estCost: 95, type: "catalog", notes: "" }], estimatedCost: 5600, createdAt: "2026-02-10" },
  { id: "r9", number: "REQ-2026-0034", title: "Triplay closet Luna", project: "Closet Luna", requester: "Carlos Ruiz", priority: "medium", status: "completed", neededBy: "2026-02-18",
    items: [{ id: "x7", itemId: "i1", name: "Triplay 18mm", qty: 6, unit: "hoja", estCost: 450, type: "catalog", notes: "" }], estimatedCost: 2700, createdAt: "2026-02-08" },
];

export const INVOICES = [
  { id: "inv1", supplier: "Maderas del Sureste", invoiceNum: "FAC-4521", date: "2026-02-23", numItems: 5, total: 8450, status: "awaiting_review", confidence: 0.94, uploadedBy: "Pavel" },
  { id: "inv2", supplier: "Herrajes y Más", invoiceNum: "HM-1190", date: "2026-02-22", numItems: 8, total: 3280, status: "saved", confidence: 0.97, uploadedBy: "Pavel" },
  { id: "inv3", supplier: "Acabados Profesionales", invoiceNum: "AP-0782", date: "2026-02-21", numItems: 3, total: 2150, status: "saved", confidence: 0.91, uploadedBy: "Carlos" },
  { id: "inv5", supplier: "Desconocido", invoiceNum: null, date: "2026-02-24", numItems: 0, total: null, status: "processing", confidence: null, uploadedBy: "Carlos" },
];

export const POS = [
  { id: "po1", number: "PO-2026-0038", supplier: "Maderas del Sureste", status: "partially_received", date: "2026-02-20", total: 8500, payment: "unpaid", numItems: 5, received: 3 },
  { id: "po2", number: "PO-2026-0037", supplier: "Herrajes y Más", status: "sent", date: "2026-02-22", total: 4200, payment: "unpaid", numItems: 6, received: 0 },
  { id: "po3", number: "PO-2026-0036", supplier: "Triplay Cancún", status: "received", date: "2026-02-15", total: 5600, payment: "paid", numItems: 4, received: 4 },
];

export const ACTIVITY = [
  { id: "a1", text: "Carlos solicitó materiales para Cocina López", type: "req", time: "25 min" },
  { id: "a2", text: "Factura Maderas del Sureste procesada (5 items)", type: "inv", time: "1 hora" },
  { id: "a3", text: "PO-0038 entrega parcial (3/5 items)", type: "del", time: "2 horas" },
  { id: "a4", text: "Stock bajo: Barniz Transparente (2 uds)", type: "alert", time: "3 horas" },
  { id: "a5", text: "Miguel solicitó acabados para Mueble TV", type: "req", time: "4 horas" },
  { id: "a6", text: "REQ-0040 aprobada por Admin", type: "ok", time: "5 horas" },
];

export const EXTRACTED_ITEMS = [
  { id: "ei1", rawDesc: "Triplay pino 18mm 4x8", match: "Triplay Pino 18mm (4×8ft)", conf: 0.95, qty: 3, unit: "hoja", price: 450, total: 1350, st: "matched" },
  { id: "ei2", rawDesc: "Bisagra oculta 35mm c/base", match: "Bisagra Oculta 35mm", conf: 0.88, qty: 20, unit: "pza", price: 38, total: 760, st: "matched" },
  { id: "ei3", rawDesc: "Torn p/madera 3 pulg", match: "Tornillo Madera 3 pulgadas", conf: 0.72, qty: 2, unit: "caja", price: 90, total: 180, st: "review" },
  { id: "ei4", rawDesc: "Pegamento blanco 1lt", match: "Pegamento Blanco 1L", conf: 0.91, qty: 3, unit: "litro", price: 180, total: 540, st: "matched" },
  { id: "ei5", rawDesc: "Jaladeras acero inox 128mm", match: null, conf: 0, qty: 12, unit: "pza", price: 85, total: 1020, st: "new" },
];

export const WITHDRAWALS = [
  { id:"w1",number:"VAL-2026-0089",status:"requested",requestedBy:"Carlos Ruiz",dispatchedBy:null,project:"Cocina López",
    items:[{id:"wi1",name:"Triplay Pino 12mm (4x8ft)",qtyReq:10,qtyDisp:null,unit:"hoja",cost:350,loc:"Rack A1",stock:3}],
    requestedAt:"08:30",dispatchedAt:null,receivedAt:null,notes:"Urgente, empezamos hoy",channel:"telegram",
    timeline:[{t:"08:30",who:"Carlos Ruiz",icon:"📤",text:"Solicito 10 hojas Triplay 12mm para Cocina Lopez",type:"request"}]},
  { id:"w2",number:"VAL-2026-0088",status:"ready",requestedBy:"Miguel Torres",dispatchedBy:"Don Beto",project:"Mueble TV Sanchez",
    items:[{id:"wi2",name:"Barniz Transparente Mate 1L",qtyReq:3,qtyDisp:2,unit:"litro",cost:320,loc:"Estante C2",stock:2},{id:"wi3",name:"Lija Grano 120",qtyReq:10,qtyDisp:10,unit:"pza",cost:25,loc:"Estante C3",stock:45}],
    requestedAt:"07:45",dispatchedAt:null,receivedAt:null,notes:"",channel:"telegram",
    timeline:[{t:"07:45",who:"Miguel Torres",icon:"📤",text:"Solicito Barniz y Lijas para Mueble TV",type:"request"},{t:"07:52",who:"Don Beto",icon:"📦",text:"Surtio parcial: 2 Barniz (solo hay 2), 10 Lijas completas",type:"dispatch"},{t:"07:52",who:"Sistema",icon:"⚠️",text:"Stock bajo: Barniz quedara en 0. Requisicion auto-creada.",type:"alert"}]},
  { id:"w3",number:"VAL-2026-0087",status:"dispatched",requestedBy:"Carlos Ruiz",dispatchedBy:"Don Beto",project:"Closet Martinez",
    items:[{id:"wi4",name:"Bisagra Oculta 35mm",qtyReq:24,qtyDisp:24,unit:"pza",cost:35,loc:"Gabinete B1",stock:120},{id:"wi5",name:"Corredera Telescopica 35cm",qtyReq:6,qtyDisp:6,unit:"par",cost:145,loc:"Gabinete B4",stock:8}],
    requestedAt:"07:15",dispatchedAt:"07:28",receivedAt:null,notes:"",channel:"telegram",
    timeline:[{t:"07:15",who:"Carlos Ruiz",icon:"📤",text:"Solicito Bisagras y Correderas para Closet",type:"request"},{t:"07:22",who:"Don Beto",icon:"✅",text:"Surtio completo",type:"dispatch"},{t:"07:28",who:"Don Beto",icon:"🤝",text:"Entregado a Carlos",type:"handoff"},{t:"07:28",who:"Sistema",icon:"⏳",text:"Esperando confirmacion de Carlos (2h)",type:"waiting"}]},
  { id:"w4",number:"VAL-2026-0086",status:"received",requestedBy:"Miguel Torres",dispatchedBy:"Don Beto",project:"Bano Herrera",
    items:[{id:"wi6",name:"MDF 15mm (4x8ft)",qtyReq:3,qtyDisp:3,unit:"hoja",cost:280,loc:"Rack A2",stock:6}],
    requestedAt:"Ayer 14:20",dispatchedAt:"Ayer 14:35",receivedAt:"Ayer 14:38",notes:"",channel:"telegram",
    timeline:[{t:"14:20",who:"Miguel Torres",icon:"📤",text:"Solicito 3 hojas MDF",type:"request"},{t:"14:30",who:"Don Beto",icon:"✅",text:"Surtio completo",type:"dispatch"},{t:"14:35",who:"Don Beto",icon:"🤝",text:"Entregado",type:"handoff"},{t:"14:38",who:"Miguel Torres",icon:"✅",text:"Confirmado: 3 hojas MDF",type:"confirm"},{t:"14:38",who:"Sistema",icon:"📊",text:"Stock descontado. MDF: 6 a 3",type:"system"}]},
  { id:"w6",number:"VAL-2026-0084",status:"self_service",requestedBy:"Carlos Ruiz",dispatchedBy:null,project:"Cocina Lopez",
    items:[{id:"wi9",name:"Tornillo Madera 3 pulgadas",qtyReq:1,qtyDisp:1,unit:"caja",cost:85,loc:"Gabinete B2",stock:25}],
    requestedAt:"Ayer 16:45",dispatchedAt:null,receivedAt:"Ayer 16:45",notes:"Don Beto ya se habia ido",channel:"telegram",
    timeline:[{t:"16:45",who:"Carlos Ruiz",icon:"🔓",text:"Auto-servicio: Tomo 1 caja Tornillos. Almacenista ausente.",type:"self"},{t:"16:45",who:"Sistema",icon:"📊",text:"Stock descontado",type:"system"},{t:"16:45",who:"Sistema",icon:"🏷️",text:"Marcado auto-servicio",type:"flag"}]},
  { id:"w7",number:"VAL-2026-0083",status:"partial",requestedBy:"Miguel Torres",dispatchedBy:"Don Beto",project:"Librero Garcia",
    items:[{id:"wi10",name:"Tabla Pino 2x4 (8ft)",qtyReq:12,qtyDisp:8,unit:"pieza",cost:95,loc:"Rack A3",stock:18}],
    requestedAt:"Ayer 10:00",dispatchedAt:"Ayer 10:15",receivedAt:"Ayer 10:18",notes:"Solo hay 8",channel:"telegram",
    timeline:[{t:"10:00",who:"Miguel Torres",icon:"📤",text:"Solicito 12 Tablas Pino",type:"request"},{t:"10:10",who:"Don Beto",icon:"⚠️",text:"Solo hay 8. Surtio 8 de 12.",type:"partial"},{t:"10:18",who:"Miguel Torres",icon:"✅",text:"Confirmado: 8 tablas",type:"confirm"},{t:"10:18",who:"Sistema",icon:"📋",text:"Requisicion auto por 4 faltantes",type:"system"}]},
];
